#!/usr/bin/env bash
# Build the offline bundle. RUN THIS WHILE YOU STILL HAVE INTERNET.
#
# Everything the target machine needs, gathered into the repository so it can
# be copied to an air-gapped box and installed with no network at all:
#
#   offline/wheelhouse/     every Python wheel, including PyTorch CPU
#   offline/models/         the trained GNN and stacker weights
#   offline/intel/          the IP intelligence snapshot + its manifest
#   web/dist/               the built console (no npm needed at install time)
#   offline/bundle.json     what was built, for what, and the hash of each file
#
#   offline/build_wheelhouse.sh                        # for this machine's Python
#   offline/build_wheelhouse.sh --python-version 3.12  # for the demo machine's
#   offline/build_wheelhouse.sh --no-gnn               # skip torch (~250 MB)
#   offline/build_wheelhouse.sh --skip-web --skip-intel
#
# WHEELS ARE BUILT FOR ONE PYTHON VERSION. A wheelhouse built for 3.14 will not
# install on 3.12 — the tags do not match and pip will say only "no matching
# distribution", which is the least helpful error it has. Check the target
# machine first (`python3 -V`) and pass --python-version if it differs.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PYTHON="${PYTHON:-$ROOT/.venv/bin/python}"
[ -x "$PYTHON" ] || PYTHON="$(command -v python3)"
RUNNING_VERSION="$("$PYTHON" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

TARGET_VERSION="$RUNNING_VERSION"
PLATFORM="${PLATFORM:-manylinux2014_x86_64}"
TORCH_INDEX="${TORCH_INDEX:-https://download.pytorch.org/whl/cpu}"
WITH_GNN=1; DO_WEB=1; DO_INTEL=1

while [ $# -gt 0 ]; do
  case "$1" in
    --python-version) TARGET_VERSION="$2"; shift 2 ;;
    --platform)       PLATFORM="$2"; shift 2 ;;
    --no-gnn)         WITH_GNN=0; shift ;;
    --skip-web)       DO_WEB=0; shift ;;
    --skip-intel)     DO_INTEL=0; shift ;;
    -h|--help)        sed -n '2,25p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

WHEELHOUSE="$ROOT/offline/wheelhouse"
say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

# --- 0. fail fast if this is being run on the machine that has no network ---
say "checking for internet"
# A HEAD request for one small package page. Asking for /simple/ instead
# downloads the entire index — 46 MB — and times out on a normal connection,
# which reads as "no internet" on a machine that has plenty.
if ! curl -fsSI --max-time 15 -o /dev/null https://pypi.org/simple/pip/; then
  cat >&2 <<'MSG'
pypi.org is not reachable.

This script is the ONLINE half of the offline install: it downloads everything
the air-gapped machine will need. Run it on a machine with internet, then copy
the whole repository across and run offline/install.sh there.
MSG
  exit 1
fi
echo "ok"

# --- 1. what to download ---------------------------------------------------
# One source of truth: pyproject's dependency list, not a second copy of it
# that drifts. The extras are named so the requirements file says why each
# group is there.
say "resolving dependencies from pyproject.toml"
"$PYTHON" - "$WITH_GNN" > offline/requirements.txt <<'PY'
import sys, tomllib
from pathlib import Path

with_gnn = sys.argv[1] == "1"
project = tomllib.loads(Path("pyproject.toml").read_text())["project"]
extras = project.get("optional-dependencies", {})

groups = [("core — ingest, graph, features, rules, fusion", project["dependencies"]),
          ("api — the console's backend and the PDF report", extras.get("api", [])),
          ("dev — the test suite, run as part of the offline checklist", extras.get("dev", []))]
if with_gnn:
    groups.append(("gnn — torch comes from the PyTorch CPU index, see the script",
                   extras.get("gnn", [])))

lines = ["# Generated by offline/build_wheelhouse.sh from pyproject.toml.",
         "# Edit pyproject.toml, not this file.", ""]
for label, requirements in groups:
    if not requirements:
        continue
    lines.append(f"# {label}")
    lines += sorted(requirements)
    lines.append("")
print("\n".join(lines))
PY
grep -vc '^\s*\(#\|$\)' offline/requirements.txt | xargs printf '%s requirement(s)\n'

# --- 2. the wheels ---------------------------------------------------------
mkdir -p "$WHEELHOUSE"
# Cross-version downloads need pip told exactly what to target, and pip only
# accepts that with --only-binary (it cannot build an sdist for another
# interpreter). Same-version downloads are left to resolve normally.
cross=()
if [ "$TARGET_VERSION" != "$RUNNING_VERSION" ]; then
  cross=(--python-version "$TARGET_VERSION" --platform "$PLATFORM" --only-binary=:all:)
  echo "cross-building for Python $TARGET_VERSION on $PLATFORM (this machine runs $RUNNING_VERSION)"
fi

if [ "$WITH_GNN" = 1 ]; then
  say "downloading PyTorch (CPU build) from $TORCH_INDEX"
  # The CPU index carries torch and nothing else, so it is fetched on its own:
  # pointing the whole resolve at it would fail to find pandas.
  torch_spec="$(grep -oE '^torch[><=!~ ]*[0-9.]*' offline/requirements.txt | head -1 || echo torch)"
  "$PYTHON" -m pip download "$torch_spec" \
      --index-url "$TORCH_INDEX" --dest "$WHEELHOUSE" "${cross[@]}"
fi

say "downloading everything else from PyPI"
# torch is already in the wheelhouse; --find-links lets pip satisfy
# torch-geometric's requirement from there instead of pulling the CUDA build.
"$PYTHON" -m pip download -r offline/requirements.txt \
    --dest "$WHEELHOUSE" --find-links "$WHEELHOUSE" "${cross[@]}"

count=$(find "$WHEELHOUSE" -name '*.whl' | wc -l)
sdists=$(find "$WHEELHOUSE" \( -name '*.tar.gz' -o -name '*.zip' \) | wc -l)
size=$(du -sh "$WHEELHOUSE" | cut -f1)
echo "$count wheel(s), $sdists source archive(s), $size"
if [ "$sdists" != "0" ]; then
  cat >&2 <<'MSG'

warning: the wheelhouse contains source archives, not just wheels. Installing
those on the target machine needs a compiler and, for some packages, network
access to fetch build dependencies — which defeats the point. Re-run with
--platform set to match the target, or install a newer pip here.
MSG
fi

# --- 3. the intelligence snapshot (phase 5e) -------------------------------
if [ "$DO_INTEL" = 1 ]; then
  say "fetching IP intelligence (offline/fetch_intel.sh)"
  # This is the only other thing in the system that ever touches the network,
  # so it belongs in the online step, not on the target machine.
  ./offline/fetch_intel.sh data/intel || echo "intel fetch incomplete — see above" >&2
  mkdir -p offline/intel
  cp -f data/intel/* offline/intel/ 2>/dev/null || true
  ls -1 offline/intel | sed 's/^/  /'
fi

# --- 4. the console --------------------------------------------------------
if [ "$DO_WEB" = 1 ]; then
  say "building the console"
  if command -v npm >/dev/null 2>&1; then
    # Shipping web/dist means the target machine needs no npm and no
    # node_modules: the built files are plain static assets that FastAPI
    # serves itself.
    npm --prefix web ci
    npm --prefix web run build
    npm --prefix web run check:offline
  else
    echo "npm not found — keeping the existing web/dist" >&2
  fi
  [ -f web/dist/index.html ] || { echo "web/dist/index.html is missing" >&2; exit 1; }
fi

# --- 5. the trained weights ------------------------------------------------
say "staging model weights"
mkdir -p offline/models
copied=0
for path in models/*.joblib models/*.pt models/*.json; do
  [ -e "$path" ] || continue
  cp -f "$path" offline/models/ && copied=$((copied + 1))
done
if [ "$copied" = 0 ]; then
  cat >&2 <<'MSG'
no trained models found in models/.

The bundle will install and run, but the fusion stacker falls back to the
configured risk weights and the GNN engine scores nothing. Train them first:

  python -m fusion.pipeline          # writes models/stacker.joblib
  python -m engines.gnn.train        # writes the GNN weights
MSG
else
  echo "$copied file(s) staged into offline/models/"
fi

# --- 6. what was built -----------------------------------------------------
say "writing offline/bundle.json"
"$PYTHON" - "$TARGET_VERSION" "$PLATFORM" "$WITH_GNN" <<'PY'
import hashlib, json, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path

target, platform, with_gnn = sys.argv[1], sys.argv[2], sys.argv[3] == "1"

def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()

def catalogue(directory: Path, pattern: str = "*") -> dict:
    return {p.name: {"bytes": p.stat().st_size, "sha256": digest(p)}
            for p in sorted(directory.glob(pattern)) if p.is_file()}

try:
    commit = subprocess.run(["git", "rev-parse", "--short=7", "HEAD"],
                            capture_output=True, text=True, check=True).stdout.strip()
except Exception:
    commit = "unknown"

wheelhouse = Path("offline/wheelhouse")
bundle = {
    "built_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    "commit": commit,
    # install.sh checks this against the interpreter it is given: a wheelhouse
    # built for another Python fails with pip's unhelpful "no matching
    # distribution", and this turns that into a sentence someone can act on.
    "python_version": target,
    "platform": platform,
    "gnn_included": with_gnn,
    "wheels": len(list(wheelhouse.glob("*.whl"))),
    "wheelhouse_bytes": sum(p.stat().st_size for p in wheelhouse.glob("*") if p.is_file()),
    "models": catalogue(Path("offline/models")) if Path("offline/models").is_dir() else {},
    "intel": catalogue(Path("offline/intel")) if Path("offline/intel").is_dir() else {},
    "console_built": Path("web/dist/index.html").exists(),
}
Path("offline/bundle.json").write_text(json.dumps(bundle, indent=2) + "\n")
print(json.dumps({k: v for k, v in bundle.items() if k not in ("models", "intel")}, indent=2))
PY

cat <<MSG

Bundle ready. To move it to the air-gapped machine:

  tar czf btc-intel-offline.tar.gz \\
      --exclude .git --exclude web/node_modules --exclude .venv \\
      --exclude vendor -C "$(dirname "$ROOT")" "$(basename "$ROOT")"

Then on that machine:  ./offline/install.sh

One thing this cannot fetch for you: the MaxMind GeoLite2 databases, which
need a free account. See offline/GEOIP_SETUP.md — the system runs without
them, with the country and ASN columns empty.
MSG
