"""A one-page PDF case report for a single entity.

ReportLab, drawing the subgraph straight onto the canvas rather than rendering
an image with a plotting library — one fewer dependency, and vector output that
stays readable when the page is printed for a file.

The report is a summary of what the system found, not a conclusion. Every
number on it is a lead; the caveat at the bottom says so, and stays on the page.
"""

from __future__ import annotations

from datetime import datetime
from io import BytesIO

import networkx as nx

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas as pdf_canvas

from .format_id import format_id

MARGIN = 20 * mm
WIDTH, HEIGHT = A4

INK = HexColor("#111318")
MUTED = HexColor("#5b6472")
RULE = HexColor("#c8cdd6")
NODE_COLOURS = {"wallet": HexColor("#2f6f4f"), "transaction": HexColor("#3a5ba0"),
                "ip": HexColor("#8a5a2b")}
FOCUS = HexColor("#b3261e")

CAVEAT = ("Generated by btc-intel from synthetic/offline data. Risk scores rank leads "
          "for a human analyst; they are not evidence of wrongdoing and no entity here "
          "has been attributed to a person. An IP candidate marked an anonymized entry "
          "point is where a broadcast entered the network, not who sent it.")


def _wrap(c, text: str, x: float, y: float, width: float, size: float = 9.5,
          leading: float = 12.5, colour=INK, font: str = "Helvetica") -> float:
    c.setFont(font, size)
    c.setFillColor(colour)
    for line in simpleSplit(str(text), font, size, width):
        c.drawString(x, y, line)
        y -= leading
    return y


def _heading(c, text: str, y: float) -> float:
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(MUTED)
    c.drawString(MARGIN, y, text.upper())
    c.setStrokeColor(RULE)
    c.line(MARGIN, y - 4, WIDTH - MARGIN, y - 4)
    return y - 16


def _layout(nodes: list[dict], edges: list[dict], box: tuple[float, float, float, float],
            given: dict[str, dict] | None = None) -> dict[str, tuple[float, float]]:
    """Positions from networkx's spring layout, rescaled into the box.

    `given` short-circuits it: when the analyst saved an investigation, the
    report draws the arrangement they built rather than a fresh one, which is
    the difference between a report of the case and a picture of the data.
    """
    x0, y0, w, h = box
    if given:
        points = {n["data"]["id"]: given[n["data"]["id"]]
                  for n in nodes if n["data"]["id"] in given}
        if points:
            xs = [p["x"] for p in points.values()]
            ys = [p["y"] for p in points.values()]
            span_x = (max(xs) - min(xs)) or 1.0
            span_y = (max(ys) - min(ys)) or 1.0
            # PDF y grows upward, the screen's grows down — flip it.
            return {node: (x0 + (p["x"] - min(xs)) / span_x * w,
                           y0 + h - (p["y"] - min(ys)) / span_y * h)
                    for node, p in points.items()}
    g = nx.Graph()
    g.add_nodes_from(n["data"]["id"] for n in nodes)
    g.add_edges_from((e["data"]["source"], e["data"]["target"]) for e in edges)
    if not g:
        return {}
    pos = nx.spring_layout(g, seed=0)
    xs = [p[0] for p in pos.values()]
    ys = [p[1] for p in pos.values()]
    span_x = (max(xs) - min(xs)) or 1.0
    span_y = (max(ys) - min(ys)) or 1.0
    return {node: (x0 + (p[0] - min(xs)) / span_x * w,
                   y0 + (p[1] - min(ys)) / span_y * h) for node, p in pos.items()}


def _draw_graph(c, graph: dict, y_top: float, height: float) -> None:
    nodes = graph["elements"]["nodes"][:60]
    positions = graph.get("positions")
    keep = {n["data"]["id"] for n in nodes}
    edges = [e for e in graph["elements"]["edges"]
             if e["data"]["source"] in keep and e["data"]["target"] in keep]
    box = (MARGIN + 6, y_top - height + 6, WIDTH - 2 * MARGIN - 12, height - 12)
    c.setStrokeColor(RULE)
    c.rect(MARGIN, y_top - height, WIDTH - 2 * MARGIN, height)
    pos = _layout(nodes, edges, box, positions)

    c.setLineWidth(0.4)
    c.setStrokeColor(RULE)
    for edge in edges:
        a, b = pos.get(edge["data"]["source"]), pos.get(edge["data"]["target"])
        if a and b:
            c.line(a[0], a[1], b[0], b[1])
    for node in nodes:
        data = node["data"]
        placed = pos.get(data["id"])
        if placed is None:          # a saved view can hold a node the layout skipped
            continue
        x, y = placed
        focus = data.get("is_focus")
        c.setFillColor(FOCUS if focus else NODE_COLOURS.get(data["type"], MUTED))
        radius = 3.6 if focus else 2.4
        c.circle(x, y, radius, stroke=0, fill=1)

    c.setFont("Helvetica", 7.5)
    c.setFillColor(MUTED)
    legend = ((f"{graph.get('source_label')} · " if graph.get("source_label") else "")
              + f"green wallets {graph['counts']['wallets']} · "
              f"blue transactions {graph['counts']['transactions']} · "
              f"brown IPs {graph['counts']['ips']} · red = this entity · "
              f"within {graph['hops']} hops"
              + (" (truncated)" if graph.get("truncated") else ""))
    c.drawString(MARGIN + 4, y_top - height + 4, legend)


def render_pdf(detail: dict, graph: dict, now: datetime) -> bytes:
    """One page: who, how risky, why, what the evidence is, and the neighbourhood."""
    buffer = BytesIO()
    c = pdf_canvas.Canvas(buffer, pagesize=A4)
    c.setTitle(f"btc-intel case report — {detail['entity_id']}")
    width = WIDTH - 2 * MARGIN
    y = HEIGHT - MARGIN

    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(INK)
    c.drawString(MARGIN, y, "btc-intel case report")
    c.setFont("Helvetica", 9)
    c.setFillColor(MUTED)
    c.drawRightString(WIDTH - MARGIN, y, now.strftime("%Y-%m-%d %H:%M:%S UTC"))
    y -= 22

    score = detail["scores"].get("risk_score")
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(INK)
    c.drawString(MARGIN, y, f"Entity {format_id(detail['entity_id'], head=20, tail=8)}")
    c.drawRightString(WIDTH - MARGIN, y,
                      f"risk score {score:.3f}" if isinstance(score, (int, float))
                      else "not alerted")
    y -= 14
    c.setFont("Helvetica", 9)
    c.setFillColor(MUTED)
    c.drawString(MARGIN, y, f"{detail['entity_type']} · {len(detail['wallets'])} wallet(s)"
                 + (f" · top signal {detail['scores']['top_signal']}"
                    if detail["scores"].get("top_signal") else "")
                 + (f" · {', '.join(detail['pattern_types'])}"
                    if detail.get("pattern_types") else ""))
    y -= 22

    y = _heading(c, "reason", y)
    y = _wrap(c, detail.get("reason") or "No alert was raised for this entity.",
              MARGIN, y, width) - 10

    y = _heading(c, "evidence", y)
    evidence = list(detail.get("evidence") or [])[:10]
    if not evidence:
        y = _wrap(c, "—", MARGIN, y, width, colour=MUTED)
    for item in evidence:
        # Shortened exactly as the console shortened it, so a reader can match
        # a line in the report to a row on the screen.
        y = _wrap(c, f"• {format_id(item, head=18, tail=8)}", MARGIN, y, width,
                  size=8.5, leading=11)
    y -= 10

    if detail.get("taint_path"):
        y = _heading(c, "taint path", y)
        y = _wrap(c, " → ".join(format_id(step) for step in detail["taint_path"]),
                  MARGIN, y, width, size=8.5) - 10

    leads = detail.get("leads") or []
    if leads:
        y = _heading(c, "attribution leads", y)
        for lead in leads[:3]:
            y = _wrap(c, f"• {lead['ip']} ({lead.get('label', lead.get('ip_class'))}, "
                         f"confidence {lead.get('confidence')})",
                      MARGIN, y, width, size=8.5, leading=11)
        y -= 10

    graph_height = max(y - MARGIN - 52, 90)
    y = _heading(c, "neighbourhood", y)
    _draw_graph(c, graph, y + 2, min(graph_height, y - MARGIN - 46))
    y = y + 2 - min(graph_height, y - MARGIN - 46) - 14

    _wrap(c, CAVEAT, MARGIN, max(y, MARGIN + 24), width, size=7.5, leading=9.5,
          colour=MUTED, font="Helvetica-Oblique")

    c.showPage()
    c.save()
    return buffer.getvalue()
